/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pajic.view.form;

import com.pajic.validation.TextFieldVerifier;
import com.pajic.view.component.TableModelOdgovori;

import javax.swing.JDialog;

/**
 *
 * @author pajic
 */
public class AddOdgovorPanel extends javax.swing.JPanel {
    
    private final JDialog dialog;
    private final TableModelOdgovori tmo;

    /**
     * Creates new form AddOdgovorPanel
     * @param dialog
     * @param tmo
     */
    public AddOdgovorPanel(JDialog dialog, TableModelOdgovori tmo) {
        this.dialog = dialog;
        this.tmo = tmo;
        initComponents();
        prepareView();
        setVerifiers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtTekst = new javax.swing.JTextArea();
        checkBoxTacan = new javax.swing.JCheckBox();
        btnSacuvaj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        txtTekst.setColumns(20);
        txtTekst.setRows(5);
        txtTekst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTekstKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtTekst);

        checkBoxTacan.setText("Tacan");

        btnSacuvaj.setText("Sacuvaj odgovor");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel1.setText("Tekst:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBoxTacan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxTacan)
                    .addComponent(btnSacuvaj))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTekstKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTekstKeyReleased
        verify();
    }//GEN-LAST:event_txtTekstKeyReleased

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        tmo.addOdgovor(txtTekst.getText(), checkBoxTacan.isSelected());
        dialog.dispose();
    }//GEN-LAST:event_btnSacuvajActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JCheckBox checkBoxTacan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtTekst;
    // End of variables declaration//GEN-END:variables
    
    private void prepareView() {
        dialog.setTitle("Odgovor");
        btnSacuvaj.setEnabled(false);
    }
    
    private void setVerifiers() {
        txtTekst.setInputVerifier(new TextFieldVerifier(1024, false));
    }

    private void verify() {
        if (txtTekst.getInputVerifier().verify(txtTekst))
            btnSacuvaj.setEnabled(true);
        else btnSacuvaj.setEnabled(false);
    }

}
