/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pajic.view.form;

import com.pajic.model.Pitanje;
import com.pajic.validation.DigitOnlyFieldVerifier;
import com.pajic.validation.TextFieldVerifier;
import com.pajic.view.component.TableModelOdgovori;
import com.pajic.view.component.TableModelPitanja;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Pavle
 */
public class AddPitanjePanel extends javax.swing.JPanel {
    
    private final JDialog dialog;
    private final TableModelPitanja tmp;
    private TableModelOdgovori tmo;
    private Pitanje pitanje;

    /**
     * Creates new form AddPitanjePanel
     * @param dialog
     * @param tmp
     */
    public AddPitanjePanel(JDialog dialog, TableModelPitanja tmp) {
        this.dialog = dialog;
        this.tmp = tmp;
        initComponents();
        prepareView();
        setVerifiers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPoeni = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOdgovori = new javax.swing.JTable();
        btnAddOdgovor = new javax.swing.JButton();
        btnDeleteOdgovor = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTekst = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Tekst");

        jLabel2.setText("Poeni");

        txtPoeni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPoeniKeyReleased(evt);
            }
        });

        tableOdgovori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableOdgovori);

        btnAddOdgovor.setText("Dodaj odgovor");
        btnAddOdgovor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOdgovorActionPerformed(evt);
            }
        });

        btnDeleteOdgovor.setText("Obrisi izabrani odgovor");
        btnDeleteOdgovor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOdgovorActionPerformed(evt);
            }
        });

        btnSave.setText("Sacuvaj pitanje");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtTekst.setColumns(20);
        txtTekst.setRows(5);
        jScrollPane2.setViewportView(txtTekst);

        jLabel3.setText("Odgovori");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDeleteOdgovor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(btnAddOdgovor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(txtPoeni)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPoeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddOdgovor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteOdgovor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddOdgovorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOdgovorActionPerformed
        JDialog dialog2 = new JDialog(dialog, true);
        dialog2.add(new AddOdgovorPanel(dialog2, tmo));
        dialog2.setLocationRelativeTo(null);
        dialog2.pack();
        dialog2.setVisible(true);
    }//GEN-LAST:event_btnAddOdgovorActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        pitanje.setTekst(txtTekst.getText());
        pitanje.setPoeni(Integer.parseInt(txtPoeni.getText()));
        pitanje.setListaOdgovora(tmo.getOdgovorList());
        tmp.addPitanje(txtTekst.getText(), Double.parseDouble(txtPoeni.getText()), tmo.getOdgovorList());
        dialog.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtPoeniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPoeniKeyReleased
        verify();
    }//GEN-LAST:event_txtPoeniKeyReleased

    private void btnDeleteOdgovorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOdgovorActionPerformed
        int selectedRow = tableOdgovori.getSelectedRow();
        if (selectedRow >= 0) {
            tmo.removeOdgovor(selectedRow);
            if (tmp.getPitanjeList().contains(pitanje)) {
                tmp.removeOdgovorFromPitanje(selectedRow, pitanje);
            }
        }
        else JOptionPane.showMessageDialog(this, "Odgovor nije izabran");
    }//GEN-LAST:event_btnDeleteOdgovorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOdgovor;
    private javax.swing.JButton btnDeleteOdgovor;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableOdgovori;
    private javax.swing.JTextField txtPoeni;
    private javax.swing.JTextArea txtTekst;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        dialog.setTitle("Pitanje");
        pitanje = new Pitanje();
        tmo = new TableModelOdgovori();
        tableOdgovori.setModel(tmo);
        btnSave.setEnabled(false);
        txtTekst.requestFocusInWindow();
    }
    
    private void setVerifiers() {
        txtPoeni.setInputVerifier(new DigitOnlyFieldVerifier(2, false, 99));
        txtTekst.setInputVerifier(new TextFieldVerifier(1024, false));
    }

    private void verify() {
        if (txtTekst.getInputVerifier().verify(txtTekst) && txtPoeni.getInputVerifier().verify(txtPoeni))
            btnSave.setEnabled(true);
        else btnSave.setEnabled(false);
    }
}
