/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pajic.view.form;

import com.pajic.communication.Operation;
import com.pajic.communication.Request;
import com.pajic.communication.Response;
import com.pajic.model.Korisnik;
import com.pajic.model.Rezultat;
import com.pajic.model.TestZnanja;

import java.io.IOException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author pajic
 */
public class AddRezultatPanel extends javax.swing.JPanel {

    private final TestZnanja testZnanja;
    private final Korisnik korisnik;
    private final TestZnanjaFrame frame;
    private final MainFrame mainFrame;
    private final JDialog dialog;
    private final int ukupnoPoena;
    private final int maxPoena;
    private boolean prosao;
    
    /**
     * Creates new form RezultatPanel
     * @param mainFrame
     * @param frame
     * @param dialog
     * @param testZnanja
     * @param korisnik
     * @param ukupnoPoena
     * @param maxPoena
     */
    public AddRezultatPanel(MainFrame mainFrame, TestZnanjaFrame frame, JDialog dialog, TestZnanja testZnanja, Korisnik korisnik, int ukupnoPoena, int maxPoena) {
        this.mainFrame = mainFrame;
        this.testZnanja = testZnanja;
        this.korisnik = korisnik;
        this.frame = frame;
        this.dialog = dialog;
        this.ukupnoPoena = ukupnoPoena;
        this.maxPoena = maxPoena;
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRezultat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblKorisnik = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTest = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPoeni = new javax.swing.JLabel();
        btnZavrsi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblProlaz = new javax.swing.JLabel();

        lblRezultat.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblRezultat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRezultat.setText("jLabel1");

        jLabel1.setText("Korisnik:");

        lblKorisnik.setText("jLabel2");

        jLabel3.setText("Test:");

        lblTest.setText("jLabel4");

        jLabel5.setText("Poeni:");

        lblPoeni.setText("jLabel6");

        btnZavrsi.setText("Zavrsi test");
        btnZavrsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZavrsiActionPerformed(evt);
            }
        });

        jLabel2.setText("Prolaz:");

        lblProlaz.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnZavrsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRezultat, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTest))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblKorisnik))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPoeni))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblProlaz)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRezultat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblKorisnik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblPoeni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblProlaz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnZavrsi)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnZavrsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZavrsiActionPerformed
        Rezultat rezultat = new Rezultat();
        rezultat.setProsao(prosao);
        rezultat.setKorisnik(korisnik);
        rezultat.setBrojPoena(ukupnoPoena);
        rezultat.setTestZnanja(testZnanja);
        rezultat.setDatumRada(LocalDate.now());
        Request request = new Request();
        request.setData(rezultat);
        request.setOperation(Operation.ADD_REZULTAT);
        try {
            mainFrame.getClient().sendRequest(request);
            Response response = mainFrame.getClient().receiveResponse();
            if (response.getException() == null) JOptionPane.showMessageDialog(this, "Rezultat je uspesno dodat");
            else JOptionPane.showMessageDialog(this, "Rezultat nije dodat\n" + response.getException().getMessage());
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(AddRezultatPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        dialog.dispose();
        frame.dispose();
    }//GEN-LAST:event_btnZavrsiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnZavrsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblKorisnik;
    private javax.swing.JLabel lblPoeni;
    private javax.swing.JLabel lblProlaz;
    private javax.swing.JLabel lblRezultat;
    private javax.swing.JLabel lblTest;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        lblKorisnik.setText(korisnik.getIme() + " " + korisnik.getPrezime());
        lblPoeni.setText(String.valueOf(ukupnoPoena + "/" + maxPoena));
        lblProlaz.setText(String.valueOf(testZnanja.getPoeniZaProlaz()));
        lblTest.setText(testZnanja.getNaziv());
        if (ukupnoPoena >= testZnanja.getPoeniZaProlaz()) {
            lblRezultat.setText("PROSAO");
            prosao = true;
        }
        else {
            lblRezultat.setText("PAO");
            prosao = false;
        }
    }
}
