/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pajic.view.form;

import com.pajic.client.Client;
import com.pajic.model.Administrator;
import com.pajic.model.GenericUser;
import com.pajic.model.Korisnik;
import com.pajic.model.Urednik;

import java.awt.BorderLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;

/**
 *
 * @author Pavle
 */
public class MainFrame extends javax.swing.JFrame {
    
    private final Client client;
    private LoginPanel loginPanel;
    private MenuPanel menuPanel;
    private GenericUser currentUser;
    /**
     * Creates new form MainWindow
     * @throws IOException
     */
    
    public MainFrame() throws IOException {
        client = new Client();
        initComponents();
        this.setTitle("TesterZnanja");
        menuBar.setVisible(false);
        menuUrednici.setVisible(false);
        menuTestoviUrednik.setVisible(false);
        menuTestoviKorisnik.setVisible(false);
        client.connect();
        login();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuUrednici = new javax.swing.JMenu();
        itemAddUrednik = new javax.swing.JMenuItem();
        itemManageUrednici = new javax.swing.JMenuItem();
        menuTestoviUrednik = new javax.swing.JMenu();
        itemAddTestZnanja = new javax.swing.JMenuItem();
        itemManageTestoviZnanja = new javax.swing.JMenuItem();
        menuTestoviKorisnik = new javax.swing.JMenu();
        itemPokreniTestZnanja = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuUrednici.setText("Urednici");

        itemAddUrednik.setText("Dodaj urednika");
        itemAddUrednik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddUrednikActionPerformed(evt);
            }
        });
        menuUrednici.add(itemAddUrednik);

        itemManageUrednici.setText("Upravljaj urednicima...");
        itemManageUrednici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemManageUredniciActionPerformed(evt);
            }
        });
        menuUrednici.add(itemManageUrednici);

        menuBar.add(menuUrednici);

        menuTestoviUrednik.setText("Testovi znanja");

        itemAddTestZnanja.setText("Kreiraj test znanja");
        itemAddTestZnanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddTestZnanjaActionPerformed(evt);
            }
        });
        menuTestoviUrednik.add(itemAddTestZnanja);

        itemManageTestoviZnanja.setText("Upravljaj testovima znanja...");
        itemManageTestoviZnanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemManageTestoviZnanjaActionPerformed(evt);
            }
        });
        menuTestoviUrednik.add(itemManageTestoviZnanja);

        menuBar.add(menuTestoviUrednik);

        menuTestoviKorisnik.setText("Testovi znanja");

        itemPokreniTestZnanja.setText("Pokreni test znanja");
        itemPokreniTestZnanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPokreniTestZnanjaActionPerformed(evt);
            }
        });
        menuTestoviKorisnik.add(itemPokreniTestZnanja);

        menuBar.add(menuTestoviKorisnik);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemManageUredniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemManageUredniciActionPerformed
        JDialog dialog = new JDialog(this, true);
        try {
            dialog.add(new UredniciManagementPanel(this, dialog, currentUser));
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        dialog.setLocationRelativeTo(null);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_itemManageUredniciActionPerformed

    private void itemAddUrednikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddUrednikActionPerformed
        JDialog dialog = new JDialog(this, true);
        dialog.add(new AddUrednikPanel(this, dialog, currentUser));
        dialog.setLocationRelativeTo(null);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_itemAddUrednikActionPerformed

    private void itemAddTestZnanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddTestZnanjaActionPerformed
        JDialog dialog = new JDialog(this, true);
        dialog.add(new AddTestZnanjaPanel(this, dialog));
        dialog.setLocationRelativeTo(null);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_itemAddTestZnanjaActionPerformed

    private void itemManageTestoviZnanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemManageTestoviZnanjaActionPerformed
        JDialog dialog = new JDialog(this, true);
        try {
            dialog.add(new TestoviZnanjaManagementPanel(this, dialog));
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        dialog.setLocationRelativeTo(null);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_itemManageTestoviZnanjaActionPerformed

    private void itemPokreniTestZnanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPokreniTestZnanjaActionPerformed
        JDialog dialog = new JDialog(this, true);
        try {
            dialog.add(new TestZnanjaSelectionPanel(this, dialog, currentUser));
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        dialog.setLocationRelativeTo(null);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_itemPokreniTestZnanjaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAddTestZnanja;
    private javax.swing.JMenuItem itemAddUrednik;
    private javax.swing.JMenuItem itemManageTestoviZnanja;
    private javax.swing.JMenuItem itemManageUrednici;
    private javax.swing.JMenuItem itemPokreniTestZnanja;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuTestoviKorisnik;
    private javax.swing.JMenu menuTestoviUrednik;
    private javax.swing.JMenu menuUrednici;
    // End of variables declaration//GEN-END:variables
    
    private void login() {
        loginPanel = new LoginPanel(this);
        setLayout(new BorderLayout());
        add(loginPanel, BorderLayout.CENTER);
        pack();
        loginPanel.setVisible(true);
        validate();
        repaint();
    }
    
    public void logout() {
        menuPanel.setVisible(false);
        loginPanel.setVisible(true);
        if (menuUrednici.isVisible()) menuUrednici.setVisible(false);
        if (menuTestoviUrednik.isVisible()) menuTestoviUrednik.setVisible(false);
        if (menuTestoviKorisnik.isVisible()) menuTestoviKorisnik.setVisible(false);
    }
    
    public void determineUserType(GenericUser user) {
        menuPanel = new MenuPanel(this);
        loginPanel.setVisible(false);
        if (user instanceof Administrator administrator) loadAdministratorMenu(administrator);
        if (user instanceof Urednik urednik) loadUrednikMenu(urednik);
        if (user instanceof Korisnik korisnik) loadKorisnikMenu(korisnik);
    }

    private void loadAdministratorMenu(Administrator administrator) {
        currentUser = administrator;
        menuPanel.getLblUserType().setText("Administrator");
        menuPanel.getLblUserName().setText(administrator.getIme() + " " + administrator.getPrezime());
        menuUrednici.setVisible(true);
        presentMenu();
    }

    private void loadUrednikMenu(Urednik urednik) {
        currentUser = urednik;
        menuPanel.getLblUserType().setText("Urednik");
        menuPanel.getLblUserName().setText(urednik.getIme() + " " +  urednik.getPrezime());
        menuTestoviUrednik.setVisible(true);
        presentMenu();
    }

    private void loadKorisnikMenu(Korisnik korisnik) {
        currentUser = korisnik;
        menuPanel.getLblUserType().setText("Korisnik");
        menuPanel.getLblUserName().setText(korisnik.getIme() + " " +  korisnik.getPrezime());
        menuTestoviKorisnik.setVisible(true);
        presentMenu();
    }
    
    private void presentMenu() {
        add(menuPanel, BorderLayout.CENTER);
        menuPanel.setVisible(true);
        menuBar.setVisible(true);
        pack();
        validate();
        repaint();
    }
    
    public Client getClient() {
        return client;
    }
}
