/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pajic.view.form;

import com.pajic.model.Korisnik;
import com.pajic.model.Odgovor;
import com.pajic.model.Pitanje;
import com.pajic.model.TestZnanja;

import java.awt.Font;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JCheckBox;
import javax.swing.JDialog;

/**
 *
 * @author pajic
 */
public class TestZnanjaFrame extends javax.swing.JFrame {

    private final TestZnanja testZnanja;
    private final Korisnik korisnik;
    private final MainFrame mainFrame;
    
    private HashMap<Odgovor, JCheckBox> odgovori;
    private int pitanjeCounter = 0;
    private int ukupnoPoena = 0;
    private int maxPoena = 0;
    
    /**
     * Creates new form TestZnanjaPanel
     * @param testZnanja
     * @param korisnik
     * @param mainFrame
     */
    public TestZnanjaFrame(TestZnanja testZnanja, Korisnik korisnik, MainFrame mainFrame) {
        this.testZnanja = testZnanja;
        this.korisnik = korisnik;
        this.mainFrame = mainFrame;
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fdhgdfg = new javax.swing.JLabel();
        lblTekstPitanja = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnProveri = new javax.swing.JButton();
        btnSledecePitanje = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        hfghfg = new javax.swing.JLabel();
        fdgkj = new javax.swing.JLabel();
        lblVrednostPitanja = new javax.swing.JLabel();
        lblBrojPitanja = new javax.swing.JLabel();
        lblPoeni = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblPoeniZaProlaz = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Test znanja");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        fdhgdfg.setText("Pitanje");

        lblTekstPitanja.setText("jLabel1");
        lblTekstPitanja.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnProveri.setText("Proveri");
        btnProveri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveriActionPerformed(evt);
            }
        });

        btnSledecePitanje.setText("Slecece pitanje");
        btnSledecePitanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSledecePitanjeActionPerformed(evt);
            }
        });

        hfghfg.setText("Poeni:");

        fdgkj.setText("Vrednost:");

        lblVrednostPitanja.setText("jLabel1");

        lblBrojPitanja.setText("jLabel1");

        lblPoeni.setText("jLabel1");

        lblStatus.setText("jLabel1");

        lblPoeniZaProlaz.setText("jLabel1");

        jLabel2.setText("Prolaz:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTekstPitanja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProveri, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSledecePitanje)
                        .addGap(18, 18, 18)
                        .addComponent(lblStatus)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fdhgdfg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBrojPitanja)
                        .addGap(44, 44, 44)
                        .addComponent(fdgkj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVrednostPitanja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, Short.MAX_VALUE)
                        .addComponent(hfghfg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPoeni)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPoeniZaProlaz)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fdhgdfg)
                    .addComponent(hfghfg)
                    .addComponent(fdgkj)
                    .addComponent(lblVrednostPitanja)
                    .addComponent(lblBrojPitanja)
                    .addComponent(lblPoeni)
                    .addComponent(lblPoeniZaProlaz)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTekstPitanja, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProveri)
                    .addComponent(btnSledecePitanje)
                    .addComponent(lblStatus))
                .addContainerGap(400, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        mainFrame.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnProveriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveriActionPerformed
        boolean tacan = true;
        for (Map.Entry<Odgovor, JCheckBox> set : odgovori.entrySet()) {
            if ((set.getKey().isTacan() && !set.getValue().isSelected()) || (!set.getKey().isTacan() && set.getValue().isSelected())) {
                lblStatus.setText("Odgovor nije tacan");
                tacan = false;
                break;
            }
        }
        for (Map.Entry<Odgovor, JCheckBox> set : odgovori.entrySet()) {
            set.getValue().setSelected(set.getKey().isTacan());
            set.getValue().setEnabled(false);
        }
        if (tacan) {
            lblStatus.setText("Odgovor je tacan");
            ukupnoPoena = (int) (ukupnoPoena + testZnanja.getListaPitanja().get(pitanjeCounter).getPoeni());
            lblPoeni.setText(String.valueOf(ukupnoPoena + "/" + maxPoena));
        }
        pitanjeCounter++;
        btnProveri.setEnabled(false);
        btnSledecePitanje.setEnabled(true);
    }//GEN-LAST:event_btnProveriActionPerformed

    private void btnSledecePitanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSledecePitanjeActionPerformed
        nextPitanje();
    }//GEN-LAST:event_btnSledecePitanjeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProveri;
    private javax.swing.JButton btnSledecePitanje;
    private javax.swing.JLabel fdgkj;
    private javax.swing.JLabel fdhgdfg;
    private javax.swing.JLabel hfghfg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBrojPitanja;
    private javax.swing.JLabel lblPoeni;
    private javax.swing.JLabel lblPoeniZaProlaz;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTekstPitanja;
    private javax.swing.JLabel lblVrednostPitanja;
    // End of variables declaration//GEN-END:variables

    private void nextPitanje() {
        if (pitanjeCounter < testZnanja.getListaPitanja().size()) {
            if (!odgovori.isEmpty()) {
                for (Map.Entry<Odgovor, JCheckBox> set : odgovori.entrySet()) 
                    this.remove(set.getValue());
                odgovori.clear();
                this.repaint();
            }
            lblStatus.setText("");
            Pitanje p = testZnanja.getListaPitanja().get(pitanjeCounter);
            lblBrojPitanja.setText(String.valueOf(pitanjeCounter));
            lblVrednostPitanja.setText(String.valueOf(p.getPoeni()));
            lblTekstPitanja.setText(p.getTekst());
            int odgovorCounter = 0;
            for (Odgovor o : p.getListaOdgovora()) {
                JCheckBox checkBox = new JCheckBox();
                checkBox.setText(o.getTekst());
                checkBox.setBounds(10, 220 + odgovorCounter * 40, 790, 30);
                checkBox.setFont(new Font("Tahoma", Font.PLAIN, 11));
                checkBox.setVisible(true);
                odgovori.put(o, checkBox);
                this.add(odgovori.get(o));
                odgovorCounter++;
            }
            btnSledecePitanje.setEnabled(false);
            btnProveri.setEnabled(true);
            this.repaint();
        }
        else odrediRezultat();
    }
    
    private void odrediRezultat() {
        JDialog dialog = new JDialog(this, true);
        dialog.add(new AddRezultatPanel(mainFrame, this, dialog, testZnanja, korisnik, ukupnoPoena, maxPoena));
        dialog.setTitle("Rezultat");
        dialog.setLocationRelativeTo(null);
        dialog.pack();
        dialog.setVisible(true);
    }
    
    private void setFont() {
        btnProveri.setFont(new Font("Tahoma", Font.PLAIN, 11));
        btnSledecePitanje.setFont(new Font("Tahoma", Font.PLAIN, 11));
        lblBrojPitanja.setFont(new Font("Tahoma", Font.PLAIN, 11));
        lblPoeni.setFont(new Font("Tahoma", Font.PLAIN, 11));
        lblStatus.setFont(new Font("Tahoma", Font.PLAIN, 11));
        lblTekstPitanja.setFont(new Font("Tahoma", Font.PLAIN, 11));
        lblVrednostPitanja.setFont(new Font("Tahoma", Font.PLAIN, 11));
        fdgkj.setFont(new Font("Tahoma", Font.PLAIN, 11));
        fdhgdfg.setFont(new Font("Tahoma", Font.PLAIN, 11));
        hfghfg.setFont(new Font("Tahoma", Font.PLAIN, 11));
        jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 11));
        lblPoeniZaProlaz.setFont(new Font("Tahoma", Font.PLAIN, 11));
    }

    private void prepareView() {
        this.odgovori = new HashMap<>();
        this.setResizable(false);
        this.setTitle("Test: " + testZnanja.getNaziv());
        mainFrame.setVisible(false);
        setFont();
        lblPoeniZaProlaz.setText(String.valueOf(testZnanja.getPoeniZaProlaz()));
        lblStatus.setText("");
        for (Pitanje p : testZnanja.getListaPitanja()) maxPoena = (int) (maxPoena + p.getPoeni());
        lblPoeni.setText(String.valueOf(ukupnoPoena + "/" + maxPoena));
        nextPitanje();
    }
}
